### ISSUE TITLE
Unable to configure WooCommerce BTCPay V2 Plugin

### ISSUE THREAD

**Issue by AnathosN** [btcpayserver/woocommerce-greenfield-plugin#1]
Hi there,

I run a self hosted BTCPay Server on my RaspiBlitz. Store is set up. BTC and Lightning Wallet configured. Payments via lightning address have already been successfully received. So I assume the BTCPay server is running fine.

I have set up a WooCommerce shop recently and tried the BTCPay V1 Plugin. Even so I paired successfully I could not check out an order as I always got a HTTP Error 500 when the shop called the BTCPay Server for the invoice creation.

I discovered there is a version 2 of the WooCommerce BTCPay Plugin and I removed the old one and installed the new one (via plugins page in WP and via zip from Github)

Whenever I click on the link to configure the Plugin I get a fatal server error:

Fatal error: Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, non-static method BTCPayServerWCPlugin::initPaymentGateways() cannot be called statically in /homepages/8/d880216525/htdocs/clickandbuilds/BITCOINBAVARIA/wp-includes/class-wp-hook.php:307 Stack trace: #0 /homepages/8/d880216525/htdocs/clickandbuilds/BITCOINBAVARIA/wp-includes/plugin.php(189): WP_Hook->apply_filters(Array, Array) #1 /homepages/8/d880216525/htdocs/clickandbuilds/BITCOINBAVARIA/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(88): apply_filters('woocommerce_pay...', Array) #2 /homepages/8/d880216525/htdocs/clickandbuilds/BITCOINBAVARIA/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(70): WC_Payment_Gateways->init() #3 /homepages/8/d880216525/htdocs/clickandbuilds/BITCOINBAVARIA/wp-content/plugins/woocommerce/includes/class-wc-payment-gateways.php(43): WC_Payment_Gateways->__construct() #4 /homepages/8/d880216525/htdocs/clickandbuilds/BITCOINBAVARIA/wp-content/plugins/woocommerce/includes/class-woocommerce.php(888): WC_Payment_Gateways::instance() #5 /homepages/8/d880216525/htdocs/clickandbuilds/BITCOINBAVARIA/wp-content/plugins/woocommerce/includes/admin/class-wc-admin-menus.php(93): WooCommerce->payment_gateways() #6 /homepages/8/d880216525/htdocs/clickandbuilds/BITCOINBAVARIA/wp-includes/class-wp-hook.php(307): WC_Admin_Menus->settings_page_init('') #7 /homepages/8/d880216525/htdocs/clickandbuilds/BITCOINBAVARIA/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) #8 /homepages/8/d880216525/htdocs/clickandbuilds/BITCOINBAVARIA/wp-includes/plugin.php(474): WP_Hook->do_action(Array) #9 /homepages/8/d880216525/htdocs/clickandbuilds/BITCOINBAVARIA/wp-admin/admin.php(237): do_action('load-woocommerc...') #10 {main} thrown in /homepages/8/d880216525/htdocs/clickandbuilds/BITCOINBAVARIA/wp-includes/class-wp-hook.php on line 307

Any Idea how to solve this?
Thanks in advance.

BR,
Anathos

**Comment by ndeet** [comment]
Hi @AnathosN,

sorry for the late reply, I did not see the GitHub issue notification unfortunately. Which PHP Version do you use? I assume 8 or 8.1 as on lower versions this is only a warning and not a fatal error. Anyway, this should have been fixed with version v0.2.0 https://github.com/btcpayserver/woocommerce-greenfield-plugin/releases/tag/v0.2.0 

So if you install most recent version (as time of writing) v0.2.3 the error should be gone.

With the 500 error on v1 I'm not sure what the problem is. If you run PHP 8.0 or greater likely there is something bailing there. Let me know if you still have that problem with V2.

**Comment by AnathosN** [comment]
I have just updated the plugin and I am able to access the configuration now. Was on 0.2.0 before and PHP version is 8.1 by default, could only downgrade to 8.0 afaik.
Thanks for your good work!
