### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by benmcguire79** [btcpayserver/woocommerce-greenfield-plugin#17]
We are deploying to  the latest Woocommerce and PHP 8.1

When installing the plugin and click on settings we receive a gateway error which normally means the plugin is not compatible with PHP8.1

Can you please let me know when your plugin will support PHP 8.1.

Thank you

**Comment by ndeet** [comment]
Hi, 

can you please check your error logs for an exception, there must be some other reason. I have the plugin running with PHP 8.1 on a demo site. There is also a debug option that will print more detailed steps into a separate log.

**Comment by ZetaWaves** [comment]
> We are deploying to the latest Woocommerce and PHP 8.1
> 
> When installing the plugin and click on settings we receive a gateway error which normally means the plugin is not compatible with PHP8.1
> 
> Can you please let me know when your plugin will support PHP 8.1.
> 
> Thank you

Ben, host10 appears down. I can't get ahold of anyone. Is OneHostCloud still alive? If so, is it possible to access files and database?

**Comment by ndeet** [comment]
Closing due to no response and likely a non issue of the plugin. Feel free to reopen.
