### ISSUE TITLE
AbstractGateway::getIcon()

### ISSUE THREAD

**Issue by VardanMelik** [btcpayserver/woocommerce-greenfield-plugin#3]
Hey BTCPay community, 

I have some issue with WP Plugin: " In this case, WordPress caught an error with one of your plugins, BTCPay For Woocommerce V2." 

2022-04-07T22:05:59+00:00 CRITICAL Uncaught TypeError: BTCPayServer\WC\Gateway\AbstractGateway::getIcon(): Return value must be of type string, null returned

htdocs/wp-content/plugins/btcpay-greenfield-for-woocommerce/src/Gateway/AbstractGateway.php:187
Stack trace:

**Comment by ndeet** [comment]
Hi @VardanMelik,

thank you for giving feedback. Did you upload a custom icon for your gateway and maybe it is gone / has been deleted. Seems this could be caused by a not anymore existing image. If you could confirm or deny that it would help, thank you.

**Comment by ndeet** [comment]
Hi @VardanMelik,

I could reproduce the problem, as I thought it has to do with a deleted image failing to load. This happens if the icon you selected for your payment gateway gets deleted from the file system for some reason. I released v1.0.2 which fixes this problem. Thanks for reporting.

**Comment by VardanMelik** [comment]
Thank you, 
I solved it, with custom url, but I see you did update. 
Thx
