### ISSUE TITLE
Make review notification dismissable forever

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/woocommerce-greenfield-plugin#45]
to review notification, add two buttons "remind me later" and "stop bothering me" (dismiss forever)

**Comment by TheEMINeM** [comment]
Both buttons doesn't work!

**Comment by ndeet** [comment]
Can you try again, I had the same problem on one site, seems a caching issue, it worked after refreshing the page?

**Comment by ndeet** [comment]
I did a new release 2.6.2 which should have fixed the issues. Seems the ajax request did interfere with form submission and maybe never finished in some cases.
